version: '1.0'

services:
  app:
    image: llmchatbot_service:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - OPENAPI_API_KEY=
      - OPENAPI_ASSISTANT_ID=
      - MIDDLEWARE_ALLOW_ORIGIN_URL=https://www.theranjana.com
    volumes:
      - ./data:/app/data
    restart: always