services:
  - type: web
    name: starlette-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      ollama pull orca-mini
      ollama pull llama3.2
      python -c "from langchain_ollama import OllamaLLM; OllamaLLM(model='orca-mini', temperature=0); OllamaLLM(model='llama3.2', temperature=0)"
    startCommand: "python app.py"
    envVars:
      - key: OPENAPI_API_KEY
        fromDatabase: true
      - key: OPENAPI_ASSISTANT_ID
        fromDatabase: true
      - key: MIDDLEWARE_ALLOW_ORIGIN_URL
        fromDatabase: true